export const SEOUL = [
  { label: '상관 없음', value: 'all' },
  { label: '종로구', value: 'jongno' },
  { label: '중구', value: 'joong' },
  { label: '용산구', value: 'yongsan' },
  { label: '성동구', value: 'seungdong' },
  { label: '광진구', value: 'gwangjin' },
  { label: '동대문구', value: 'ddm' },
  { label: '중랑구', value: 'jungnang' },
  { label: '성북구', value: 'seungbook' },
  { label: '강북구', value: 'gangbuk' },
  { label: '도봉구', value: 'dobong' },
  { label: '노원구', value: 'nowon' },
  { label: '은평구', value: 'eunpyeong' },
  { label: '서대문구', value: 'sdm' },
  { label: '마포구', value: 'mapo' },
  { label: '양천구', value: 'yangcheon' },
  { label: '강서구', value: 'gangseo' },
  { label: '구로구', value: 'guro' },
  { label: '금천구', value: 'geomcheon' },
  { label: '영등포구', value: 'ydp' },
  { label: '동작구', value: 'dongjak' },
  { label: '관악구', value: 'gwanak' },
  { label: '서초구', value: 'seocho' },
  { label: '강남구', value: 'gangnam' },
  { label: '송파구', value: 'songpa' },
  { label: '강동구', value: 'gangdong' }
];
